# Pandas Continuação...

In [ ]:
# carregamento da biblioteca
import pandas as pd

In [ ]:
# carregar os dados
df = pd.read_csv('http://emsapi.esy.es/datasets/covid_19_data.csv')
df.head()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [ ]:
# carregando dados com um índice definido
# index_col: define qual será a coluna utilizada como índice
df = pd.read_csv('http://emsapi.esy.es/datasets/covid_19_data.csv', index_col=0)
df.head()

,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
SNo,,,,,,,
1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [ ]:
# Realizar a inspeção do DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 98252 entries, 1 to 98252
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ObservationDate  98252 non-null  object
 1   Province/State   67099 non-null  object
 2   Country/Region   98252 non-null  object
 3   Last Update      98252 non-null  object
 4   Confirmed        98252 non-null  float64
 5   Deaths           98252 non-null  float64
 6   Recovered        98252 non-null  float64
dtypes: float64(3), object(4)
memory usage: 6.0+ MB

In [ ]:
# E se quisermos mostrar apenas a quantidade de linhas e de colunas?
df.shape

(98252, 7)

In [ ]:
# E se quisermos mostrar 20 linhas aleatórias?
df.sample(20)

,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
SNo,,,,,,,
59094,07/08/2020,NaN,Guinea,2020-07-09 04:34:23,5697.0,34.0,4577.0
90213,08/19/2020,NaN,Portugal,2020-08-20 04:27:43,54701.0,1786.0,40129.0
77224,08/01/2020,Nebraska,US,2020-08-02 04:34:47,26391.0,332.0,0.0
39377,06/11/2020,NaN,Cameroon,2020-06-12 05:09:52,8681.0,212.0,4836.0
56536,07/04/2020,La Rioja,Spain,2020-07-05 04:33:46,4078.0,366.0,3107.0
85069,08/12/2020,Aichi,Japan,2020-08-13 04:29:15,3391.0,38.0,1345.0
92946,08/22/2020,Sikkim,India,2020-08-23 04:27:48,1381.0,3.0,871.0
67800,07/19/2020,Xinjiang,Mainland China,2020-07-20 05:34:40,77.0,3.0,73.0
92356,08/22/2020,NaN,Czech Republic,2020-08-23 04:27:48,21790.0,411.0,16087.0
83798,08/10/2020,Junin,Peru,2020-08-11 04:35:08,9723.0,496.0,0.0
51666,06/27/2020,Tokushima,Japan,2020-06-28 04:34:04,6.0,1.0,4.0
6020,03/16/2020,NaN,Cyprus,2020-03-16T02:33:08,33.0,0.0,0.0
33732,06/02/2020,Putumayo,Colombia,2020-06-03 02:33:13,9.0,1.0,1.0
74101,07/28/2020,Heilongjiang,Mainland China,2020-07-29 04:35:11,947.0,13.0,934.0
2733,02/29/2020,Gansu,Mainland China,2020-02-28T02:33:02,91.0,2.0,82.0
88846,08/17/2020,C. Valenciana,Spain,2020-08-18 04:27:56,17492.0,1443.0,9970.0
14034,04/11/2020,Anhui,Mainland China,2020-04-11 22:52:46,991.0,6.0,984.0
46925,06/21/2020,Dadra and Nagar Haveli and Daman and Diu,India,2020-06-22 04:33:20,88.0,0.0,26.0
85076,08/12/2020,Altai Republic,Russia,2020-08-13 04:29:15,1739.0,7.0,1460.0
19747,04/29/2020,NaN,San Marino,2020-04-30 02:32:27,563.0,41.0,69.0

In [ ]:
# E se precisar mostrar as cinco primeiras e as cinco últimas?
df

,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
SNo,,,,,,,
1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
...,...,...,...,...,...,...,...
98248,08/29/2020,Zaporizhia Oblast,Ukraine,2020-08-30 04:28:22,1520.0,25.0,883.0
98249,08/29/2020,Zeeland,Netherlands,2020-08-30 04:28:22,1048.0,72.0,0.0
98250,08/29/2020,Zhejiang,Mainland China,2020-08-30 04:28:22,1277.0,1.0,1268.0
98251,08/29/2020,Zhytomyr Oblast,Ukraine,2020-08-30 04:28:22,3155.0,61.0,1837.0
98252,08/29/2020,Zuid-Holland,Netherlands,2020-08-30 04:28:22,18774.0,1344.0,0.0

In [ ]:
# Vamos excluir a coluna Province/State, pois a ausência de dados pode atrapalhar
# Para isso, vamos usar o .drop()
# inplace altera os dados originais do DataFrame (sem CTRL+Z)
# axis=0 edfine que será excluída a linha, quando 1, a coluna

df.drop(['Province/State'], axis=1, inplace=True)
df.head(0) # quando n=0, mostra apenas o nome das colunas (horizontalmente)

Empty DataFrame
Columns: [ObservationDate, Country/Region, Last Update, Confirmed, Deaths, Recovered]
Index: []

In [ ]:
# Salvando a etapa (fotografia) antes de continuar com as alterações
df.to_excel('/content/corona_sem_state.xlsx')

In [ ]:
# Fiz besteira
df.drop(['Confirmed'], axis=1, inplace=True)
df.head()

    ObservationDate  Country/Region      Last Update  Deaths  Recovered
SNo
1        01/22/2020  Mainland China  1/22/2020 17:00     0.0        0.0
2        01/22/2020  Mainland China  1/22/2020 17:00     0.0        0.0
3        01/22/2020  Mainland China  1/22/2020 17:00     0.0        0.0
4        01/22/2020  Mainland China  1/22/2020 17:00     0.0        0.0
5        01/22/2020  Mainland China  1/22/2020 17:00     0.0        0.0

In [ ]:
# Vamos carregar novamente
df = pd.read_excel('/content/corona_sem_state.xlsx', index_col=0)

In [ ]:
df.head()

,ObservationDate,Country/Region,Last Update,Confirmed,Deaths,Recovered
SNo,,,,,,
1,01/22/2020,Mainland China,1/22/2020 17:00,1,0,0
2,01/22/2020,Mainland China,1/22/2020 17:00,14,0,0
3,01/22/2020,Mainland China,1/22/2020 17:00,6,0,0
4,01/22/2020,Mainland China,1/22/2020 17:00,1,0,0
5,01/22/2020,Mainland China,1/22/2020 17:00,0,0,0

In [ ]:
# Ufa, tudo normal agora!!!!

In [ ]:
# Vamos agora apagar apenas uma linha do DataFrame
df.drop(index=1, axis=0, inplace=True)
df.head()

,ObservationDate,Country/Region,Last Update,Confirmed,Deaths,Recovered
SNo,,,,,,
2,01/22/2020,Mainland China,1/22/2020 17:00,14,0,0
3,01/22/2020,Mainland China,1/22/2020 17:00,6,0,0
4,01/22/2020,Mainland China,1/22/2020 17:00,1,0,0
5,01/22/2020,Mainland China,1/22/2020 17:00,0,0,0
6,01/22/2020,Mainland China,1/22/2020 17:00,26,0,0

# Criação de subsets

In [ ]:
# podemos criar uma lista de colunas e fornecer como parâmetro do DataFrame
colunas = ['Country/Region', 'Confirmed', 'Deaths']
df[colunas].head()

     Country/Region  Confirmed  Deaths
SNo
2    Mainland China         14       0
3    Mainland China          6       0
4    Mainland China          1       0
5    Mainland China          0       0
6    Mainland China         26       0

In [ ]:
df.head(2)

,ObservationDate,Country/Region,Last Update,Confirmed,Deaths,Recovered
SNo,,,,,,
2,01/22/2020,Mainland China,1/22/2020 17:00,14,0,0
3,01/22/2020,Mainland China,1/22/2020 17:00,6,0,0

In [ ]:
# Agregar dados no DataFrame com base em dados existentes
# Criar uma nova coluna com um resultado calculado
df['Confirmed + Deaths'] = df['Confirmed'] + df['Deaths']
df.head()

,ObservationDate,Country/Region,Last Update,Confirmed,Deaths,Recovered,Confirmed + Deaths
SNo,,,,,,,
2,01/22/2020,Mainland China,1/22/2020 17:00,14,0,0,14
3,01/22/2020,Mainland China,1/22/2020 17:00,6,0,0,6
4,01/22/2020,Mainland China,1/22/2020 17:00,1,0,0,1
5,01/22/2020,Mainland China,1/22/2020 17:00,0,0,0,0
6,01/22/2020,Mainland China,1/22/2020 17:00,26,0,0,26

In [ ]:
#df.sample(10)

In [ ]:
# Crie uma nova coluna mostrando a relação entre mortes e casos confirmados
df['Death by Cases'] = df['Deaths'] / df['Confirmed']
df

,ObservationDate,Country/Region,Last Update,Confirmed,Deaths,Recovered,Confirmed + Deaths,Death by Cases
SNo,,,,,,,,
2,01/22/2020,Mainland China,1/22/2020 17:00,14,0,0,14,0.000000
3,01/22/2020,Mainland China,1/22/2020 17:00,6,0,0,6,0.000000
4,01/22/2020,Mainland China,1/22/2020 17:00,1,0,0,1,0.000000
5,01/22/2020,Mainland China,1/22/2020 17:00,0,0,0,0,NaN
6,01/22/2020,Mainland China,1/22/2020 17:00,26,0,0,26,0.000000
...,...,...,...,...,...,...,...,...
98248,08/29/2020,Ukraine,2020-08-30 04:28:22,1520,25,883,1545,0.016447
98249,08/29/2020,Netherlands,2020-08-30 04:28:22,1048,72,0,1120,0.068702
98250,08/29/2020,Mainland China,2020-08-30 04:28:22,1277,1,1268,1278,0.000783
98251,08/29/2020,Ukraine,2020-08-30 04:28:22,3155,61,1837,3216,0.019334
98252,08/29/2020,Netherlands,2020-08-30 04:28:22,18774,1344,0,20118,0.071588

In [ ]:
# Como ocorreu uma divisão por zero (NaN), precisamos substituir o valor por zero
df.fillna(0, axis=1, inplace=True)
df.head()

,ObservationDate,Country/Region,Last Update,Confirmed,Deaths,Recovered,Confirmed + Deaths,Death by Cases
SNo,,,,,,,,
2,01/22/2020,Mainland China,1/22/2020 17:00,14,0,0,14,0.0
3,01/22/2020,Mainland China,1/22/2020 17:00,6,0,0,6,0.0
4,01/22/2020,Mainland China,1/22/2020 17:00,1,0,0,1,0.0
5,01/22/2020,Mainland China,1/22/2020 17:00,0,0,0,0,0.0
6,01/22/2020,Mainland China,1/22/2020 17:00,26,0,0,26,0.0

# Conversão de valores 

.to_numeric()

.to_datetime()

.astype()

      'bool'

      'int64'

      'float64'

      'str'

      'category'
 
.replace()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 98251 entries, 2 to 98252
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ObservationDate     98251 non-null  object
 1   Country/Region      98251 non-null  object
 2   Last Update         98251 non-null  object
 3   Confirmed           98251 non-null  int64
 4   Deaths              98251 non-null  int64
 5   Recovered           98251 non-null  int64
 6   Confirmed + Deaths  98251 non-null  int64
 7   Death by Cases      98251 non-null  float64
dtypes: float64(1), int64(4), object(3)
memory usage: 6.7+ MB

In [ ]:
# Alterando o tipo de dados das colunas 0 e 2
df['ObservationDate'] = pd.to_datetime(df['ObservationDate']) 
df['Last Update'] = pd.to_datetime(df['Last Update']) 
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 98251 entries, 2 to 98252
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ObservationDate     98251 non-null  datetime64[ns]
 1   Country/Region      98251 non-null  object
 2   Last Update         98251 non-null  datetime64[ns]
 3   Confirmed           98251 non-null  int64
 4   Deaths              98251 non-null  int64
 5   Recovered           98251 non-null  int64
 6   Confirmed + Deaths  98251 non-null  int64
 7   Death by Cases      98251 non-null  float64
dtypes: datetime64[ns](2), float64(1), int64(4), object(1)
memory usage: 6.7+ MB

In [ ]:
df.head()

,ObservationDate,Country/Region,Last Update,Confirmed,Deaths,Recovered,Confirmed + Deaths,Death by Cases
SNo,,,,,,,,
2,2020-01-22,Mainland China,2020-01-22 17:00:00,14,0,0,14,0.0
3,2020-01-22,Mainland China,2020-01-22 17:00:00,6,0,0,6,0.0
4,2020-01-22,Mainland China,2020-01-22 17:00:00,1,0,0,1,0.0
5,2020-01-22,Mainland China,2020-01-22 17:00:00,0,0,0,0,0.0
6,2020-01-22,Mainland China,2020-01-22 17:00:00,26,0,0,26,0.0

In [ ]:
# Alterando valores no DataFrame
df['Country/Region'].replace('Mainland China', 'China', inplace=True)
df.sample(10)

,ObservationDate,Country/Region,Last Update,Confirmed,Deaths,Recovered,Confirmed + Deaths,Death by Cases
SNo,,,,,,,,
1415,2020-02-13,US,2020-02-01 19:43:03,1,0,0,1,0.000000
71328,2020-07-24,Russia,2020-07-25 04:47:39,5447,81,4102,5528,0.014871
50314,2020-06-26,Chad,2020-06-27 04:33:35,865,74,778,939,0.085549
1638,2020-02-16,US,2020-02-13 18:53:02,1,0,0,1,0.000000
29257,2020-05-25,China,2020-05-26 02:32:35,1019,4,1015,1023,0.003925
61655,2020-07-11,Macau,2020-07-12 04:34:30,46,0,45,46,0.000000
7925,2020-03-23,Azerbaijan,2020-03-23 23:23:20,72,1,10,73,0.013889
81652,2020-08-07,Chile,2020-08-08 04:34:53,260657,7847,246638,268504,0.030105
2060,2020-02-22,Hong Kong,2020-02-22 13:23:05,69,2,6,71,0.028986
23408,2020-05-10,France,2020-05-11 02:32:30,186,14,83,200,0.075269

In [ ]:
df.head(10)

,ObservationDate,Country/Region,Last Update,Confirmed,Deaths,Recovered,Confirmed + Deaths,Death by Cases
SNo,,,,,,,,
2,2020-01-22,China,2020-01-22 17:00:00,14,0,0,14,0.0
3,2020-01-22,China,2020-01-22 17:00:00,6,0,0,6,0.0
4,2020-01-22,China,2020-01-22 17:00:00,1,0,0,1,0.0
5,2020-01-22,China,2020-01-22 17:00:00,0,0,0,0,0.0
6,2020-01-22,China,2020-01-22 17:00:00,26,0,0,26,0.0
7,2020-01-22,China,2020-01-22 17:00:00,2,0,0,2,0.0
8,2020-01-22,China,2020-01-22 17:00:00,1,0,0,1,0.0
9,2020-01-22,China,2020-01-22 17:00:00,4,0,0,4,0.0
10,2020-01-22,China,2020-01-22 17:00:00,1,0,0,1,0.0
11,2020-01-22,China,2020-01-22 17:00:00,0,0,0,0,0.0

In [ ]:
# Substituir US por United States
df['Country/Region'].replace('US', 'United State', inplace=True)
df.sample(20)

,ObservationDate,Country/Region,Last Update,Confirmed,Deaths,Recovered,Confirmed + Deaths,Death by Cases
SNo,,,,,,,,
95972,2020-08-26,Peru,2020-08-27 04:28:15,0,0,414577,0,0.000000
2974,2020-03-02,China,2020-03-01 12:23:06,122,1,103,123,0.008197
3995,2020-03-08,South Korea,2020-03-08 12:53:03,7314,50,118,7364,0.006836
25986,2020-05-18,Burma,2020-05-19 02:32:18,191,6,101,197,0.031414
55953,2020-07-03,Canada,2020-07-04 04:33:51,55682,5560,25158,61242,0.099853
67860,2020-07-20,Dominica,2020-07-21 04:38:46,18,0,18,18,0.000000
95887,2020-08-26,France,2020-08-27 04:28:15,5,0,1,5,0.000000
71054,2020-07-24,Japan,2020-07-25 04:47:39,1433,46,1070,1479,0.032100
37426,2020-06-08,Zimbabwe,2020-06-09 03:33:03,287,4,46,291,0.013937
62546,2020-07-12,Peru,2020-07-13 04:43:04,6608,180,0,6788,0.027240
24153,2020-05-13,Burkina Faso,2020-05-14 03:32:28,773,51,592,824,0.065977
50689,2020-06-26,Ukraine,2020-06-27 04:33:35,2419,48,1236,2467,0.019843
8527,2020-03-25,Bolivia,2020-03-25 23:37:49,32,0,0,32,0.000000
71134,2020-07-24,China,2020-07-25 04:47:39,1276,22,1254,1298,0.017241
18715,2020-04-26,Guyana,2020-04-27 02:31:20,74,8,12,82,0.108108
2313,2020-02-25,China,2020-02-25 00:23:03,121,1,83,122,0.008264
29974,2020-05-27,Luxembourg,2020-05-28 02:32:31,4001,110,3791,4111,0.027493
52571,2020-06-29,Mauritius,2020-06-30 04:33:48,341,10,326,351,0.029326
83507,2020-08-10,Malawi,2020-08-11 04:35:08,4674,146,2430,4820,0.031237
17798,2020-04-23,Monaco,2020-04-24 03:31:35,94,4,35,98,0.042553

In [ ]:
df['Country/Region'].replace('United State', 'United States', inplace=True)
df.sample(20)

,ObservationDate,Country/Region,Last Update,Confirmed,Deaths,Recovered,Confirmed + Deaths,Death by Cases
SNo,,,,,,,,
12464,2020-04-06,Denmark,2020-04-06 09:37:00,11,0,4,11,0.000000
94724,2020-08-25,Brazil,2020-08-26 04:28:11,116579,3588,98916,120167,0.030777
81010,2020-08-06,United States,2020-08-07 04:35:11,19934,258,0,20192,0.012943
57158,2020-07-05,Spain,2020-07-06 04:33:57,9251,619,9204,9870,0.066912
7402,2020-03-21,Croatia,2020-03-21 17:43:03,206,1,5,207,0.004854
68422,2020-07-20,Russia,2020-07-21 04:38:46,6380,74,3995,6454,0.011599
48285,2020-06-23,India,2020-06-24 04:33:28,10002,119,4599,10121,0.011898
59201,2020-07-08,Brazil,2020-07-09 04:34:23,15167,404,8604,15571,0.026637
34608,2020-06-04,Hungary,2020-06-05 02:33:06,3954,539,2205,4493,0.136318
84865,2020-08-11,United States,2020-08-12 04:27:29,576,9,0,585,0.015625
28476,2020-05-23,China,2020-05-24 02:32:43,563,3,558,566,0.005329
95604,2020-08-26,Netherlands,2020-08-27 04:28:15,7279,688,0,7967,0.094518
53075,2020-06-29,Canada,2020-06-30 04:33:48,779,13,679,792,0.016688
33680,2020-06-02,China,2020-06-03 02:33:13,75,0,75,75,0.000000
57742,2020-07-06,Italy,2020-07-07 04:34:00,3309,464,2689,3773,0.140224
68986,2020-07-21,India,2020-07-22 04:34:42,1198,2,1010,1200,0.001669
36465,2020-06-06,China,2020-06-07 03:53:30,198,0,198,198,0.000000
45424,2020-06-19,United States,2020-06-20 04:33:19,170862,5426,0,176288,0.031757
68335,2020-07-20,United States,2020-07-21 04:38:46,101231,1677,0,102908,0.016566
64283,2020-07-15,Taiwan,2020-07-16 04:44:59,451,7,440,458,0.015521

# Filtragem de Dados

In [ ]:
df_brazil = df[df['Country/Region'] == 'Brazil'] # cria um DataFrame virtual (sem inplace)
df_brazil

,ObservationDate,Country/Region,Last Update,Confirmed,Deaths,Recovered,Confirmed + Deaths,Death by Cases
SNo,,,,,,,,
83,2020-01-23,Brazil,2020-01-23 17:00:00,0,0,0,0,0.000000
2456,2020-02-26,Brazil,2020-02-26 23:53:02,1,0,0,1,0.000000
2560,2020-02-27,Brazil,2020-02-26 23:53:02,1,0,0,1,0.000000
2669,2020-02-28,Brazil,2020-02-26 23:53:02,1,0,0,1,0.000000
2777,2020-02-29,Brazil,2020-02-29 21:03:05,2,0,0,2,0.000000
...,...,...,...,...,...,...,...,...
98104,2020-08-29,Brazil,2020-08-30 04:28:22,43299,587,11057,43886,0.013557
98121,2020-08-29,Brazil,2020-08-30 04:28:22,146404,2218,131550,148622,0.015150
98123,2020-08-29,Brazil,2020-08-30 04:28:22,801422,29944,609618,831366,0.037364
98129,2020-08-29,Brazil,2020-08-30 04:28:22,72280,1839,62950,74119,0.025443
98173,2020-08-29,Brazil,2020-08-30 04:28:22,49651,658,30701,50309,0.013253

In [ ]:
df[df['Country/Region'] == 'Mexico']

,ObservationDate,Country/Region,Last Update,Confirmed,Deaths,Recovered,Confirmed + Deaths,Death by Cases
SNo,,,,,,,,
82,2020-01-23,Mexico,2020-01-23 17:00:00,0,0,0,0,0.000000
2680,2020-02-28,Mexico,2020-02-28 15:03:26,1,0,0,1,0.000000
2767,2020-02-29,Mexico,2020-02-29 21:13:17,4,0,0,4,0.000000
2888,2020-03-01,Mexico,2020-03-01 23:33:03,5,0,0,5,0.000000
3018,2020-03-02,Mexico,2020-03-01 23:33:03,5,0,0,5,0.000000
...,...,...,...,...,...,...,...,...
98159,2020-08-29,Mexico,2020-08-30 04:28:22,24271,1779,21275,26050,0.073297
98172,2020-08-29,Mexico,2020-08-30 04:28:22,6196,896,4970,7092,0.144609
98216,2020-08-29,Mexico,2020-08-30 04:28:22,27985,3643,22837,31628,0.130177
98242,2020-08-29,Mexico,2020-08-30 04:28:22,14551,1300,11718,15851,0.089341
98246,2020-08-29,Mexico,2020-08-30 04:28:22,5195,470,3970,5665,0.090472

# Alterando Nome de Colunas

In [ ]:
df.rename(
    columns = 
    {
        'Country/Region': 'Country'
    },
    inplace=True
)
df.head(1)

,ObservationDate,Country,Last Update,Confirmed,Deaths,Recovered,Confirmed + Deaths,Death by Cases
SNo,,,,,,,,
2,2020-01-22,China,2020-01-22 17:00:00,14,0,0,14,0.0

# Manipulação de dados: remoção

* `.unique()`: retorna valores únicos
* `.duplicated()`: retorna `bool` para linhas duplicadas
* `drop_duplicated()`: retorna *DataFrame* com linhas duplicadas removidas

In [ ]:
# Quantos países existem no DataFrame
len(df['Country'].unique())

223

In [ ]:
# Quantos países estão repetidos?
sum(df.duplicated(subset=['Country']))

98028